version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/aita_invitations?replicaSet=rs0
      HOST: 0.0.0.0
    command: npm start