FROM node:10.16.3

RUN apt-get update && true 1
RUN apt-get install -y gconf-service libasound2 libatk1.0-0 \
  libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 \
  libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
  libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
  libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
  libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
  fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

RUN npm i npm@6.10.3 -g
RUN npm install pm2@3.5.1 -g

WORKDIR /src
ADD ./package.json /src/package.json
# ADD ./package.json /src/package-lock.json

RUN npm install --production

RUN rm -rf /var/cache/apk/*

ADD ./app /src/app
ADD ./config /src/config
ADD ./pm2.config.js /src/pm2.config.js

EXPOSE 3000